name: Create Tag on Version Change

on:
  push:
    branches:
      - main  # Replace with the main branch of your repository, if different

jobs:
  check_version_and_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get current version from setup.py
        id: get_version
        run: |
          VERSION=$(python -c 'import re, codecs; from setuptools import setup, find_packages; setup_py = codecs.open("setup.py", "r", "utf-8").read(); version = re.search(r"version=['\"](.+?)['\"]", setup_py).group(1); print(version)')
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"        

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git ls-remote --tags origin | grep -q "refs/tags/v${{ steps.get_version.outputs.version }}" && echo "true" || echo "false")
          echo "Tag exists: $TAG_EXISTS"
          echo "::set-output name=tag_exists::$TAG_EXISTS"

      - name: Create and push new tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git tag -a "v${{ steps.get_version.outputs.version }}" -m "Version ${{ steps.get_version.outputs.version }}"
          git push --tags
